In [5]:
import numpy as np

In [6]:
4*4

16

In [7]:
4*4+2*4+9*2

42

(4*2)+(8*7)


In [8]:
(4*2)+(8*7)

64

In [9]:
10**3

1000

In [10]:
13%2

1

In [11]:
x=100
y=200
z=300
d=x+y+z
d

600

In [12]:
y="Oil_Gas"


In [13]:
y[0]

'O'

In [14]:
y[5]


'a'

In [15]:
y[0:4]

'Oil_'

In [16]:
y[:]

'Oil_Gas'

In [17]:
y[:6]


'Oil_Ga'

In [18]:
y[2:]

'l_Gas'

In [20]:
z='The optimum well spacing is 950 ft'
len(z)

34

In [22]:
list=['Land','Geology','Drilling']

In [23]:
list


['Land', 'Geology', 'Drilling']

In [24]:
list.append('Frac')

In [25]:
list

['Land', 'Geology', 'Drilling', 'Frac']

In [26]:
list.append(1000

SyntaxError: incomplete input (4130884942.py, line 1)

In [27]:
list.append(100)

In [28]:
list

['Land', 'Geology', 'Drilling', 'Frac', 100]

In [29]:
print(list[0])
print(list[2])
print(list[len(list)-1])


Land
Drilling
100


In [30]:
list[0]='Title Search'


In [31]:
list


['Title Search', 'Geology', 'Drilling', 'Frac', 100]

In [32]:
list[2]='Augusto'

In [33]:
list

['Title Search', 'Geology', 'Augusto', 'Frac', 100]

In [34]:
nested_list=[10,20, [30,40,50,60]]

In [35]:
nested_list[2][1]

40

In [39]:
nested_list2=[10,20, [30,40,50,60, [4,3,1]]]

In [40]:
nested_list2[0]


10

In [41]:
nested_list2[2]

[30, 40, 50, 60, [4, 3, 1]]

In [42]:
nested_list2[3]

IndexError: list index out of range

In [44]:
nested_list2[2][4][1]


3

In [45]:
a={'ML_Models':['ANN','SVM','RF','GB','XGB'],
'Score':[90,85,95,90,100]}

In [46]:
a

{'ML_Models': ['ANN', 'SVM', 'RF', 'GB', 'XGB'],
 'Score': [90, 85, 95, 90, 100]}

In [47]:
a['ML_Models']

['ANN', 'SVM', 'RF', 'GB', 'XGB']

In [48]:
a['Score']

[90, 85, 95, 90, 100]

In [49]:
d={'a':{'inner_a':[1,2,3]}}

In [51]:
d

{'a': {'inner_a': [1, 2, 3]}}

In [53]:
d['a']['inner_a']


[1, 2, 3]

In [54]:
t=(100,200,300,400)

In [55]:
t

(100, 200, 300, 400)

In [56]:
t[0]='New'

TypeError: 'tuple' object does not support item assignment

In [58]:
if 100==200:
    print('Good job')
else:
    print('Not good!')

Not good!


In [64]:
X=100
Y=200
Z=300

if X>Y:
    A=X+Y
elif Z<Y:
    B=X+Y+Z
else:
    C=2*(X+Y+Z)
C

1200

In [69]:
n=float(input("Enter any number"))
if n ==0:
    print('Zero')
elif n>0:
    print('Positive Number')
else:
    print('Negative Number')


Enter any number 0


Zero


In [70]:
i=range(0,5)
for x in i:
    print(x)

0
1
2
3
4


In [72]:
for x in range(0,3):
    print('edge computing')

edge computing
edge computing
edge computing


In [75]:
Frac_Crews=['Frac_Crew_1', 'Frac_Crew_2', 'Frac_Crew_3', 'Frac_Crew_4']
for x in Frac_Crews:
    if x=='Frac_Crew_2':
        continue
    print(x)

Frac_Crew_1
Frac_Crew_3
Frac_Crew_4


In [77]:
for x in range(10, 19, 4):
    
    print(x)


10
14
18


In [80]:
Performance=["Low_Performing", "Medium_Performing", "High_Performing"]
Drilling_crews=["Drilling_Crew_1", "Drilling_Crew_2", "Drilling_Crew_3"]
for x in Performance: 
    for y in Drilling_crews:
        print(x, y)

Low_Performing Drilling_Crew_1
Low_Performing Drilling_Crew_2
Low_Performing Drilling_Crew_3
Medium_Performing Drilling_Crew_1
Medium_Performing Drilling_Crew_2
Medium_Performing Drilling_Crew_3
High_Performing Drilling_Crew_1
High_Performing Drilling_Crew_2
High_Performing Drilling_Crew_3


In [81]:
i=[10,20,30,40]
out=[]
for x in i:
    out.append(x**2+200)
print(out)

[300, 600, 1100, 1800]


In [82]:
[x**2+200 for x in i]

[300, 600, 1100, 1800]

In [83]:
y=[5,6,7,8,9,10]
[x**2+3*x+369 for x in y]


[409, 423, 439, 457, 477, 499]

In [84]:
def linear_function(n):
    return 2*n+20
linear_function(20)

60

In [85]:
def Turner_rate(x):
    return x**2+50

In [86]:
Turner_rate(20)

450

In [87]:
dictionary={'Column_1':[10,20,30], 'Column_2':[40,50,60], 'Column_3':[70,80,90]}
dictionary

{'Column_1': [10, 20, 30], 'Column_2': [40, 50, 60], 'Column_3': [70, 80, 90]}

In [88]:
import pandas as pd
dictionary=pd.DataFrame(dictionary)
dictionary

Column_1  Column_2  Column_3
0        10        40        70
1        20        50        80
2        30        60        90

In [91]:
dictionary=pd.DataFrame({'Column_1':[10,20,30], 'Column_2':[40,50,60], 'Column_3':[70,80,90]})
dictionary

Column_1  Column_2  Column_3
0        10        40        70
1        20        50        80
2        30        60        90

In [95]:
CAPEX=pd.DataFrame({'Drilling_CAPEX':[2000000,2200000,2100000], 'Completions_CAPEX':[5000000,5100000,5150000], 'Production_\
                    CAPEX':[500000,550000,450000]}, index=['Well_1', 'Well_2', 'Well_3'])
CAPEX

Drilling_CAPEX  Completions_CAPEX  \
Well_1         2000000            5000000   
Well_2         2200000            5100000   
Well_3         2100000            5150000   

        Production_                    CAPEX  
Well_1                                500000  
Well_2                                550000  
Well_3                                450000

In [107]:
from numpy.random import randn
import numpy as np
seed=100
np.random.seed(seed)
life_cycle=pd.DataFrame(randn(8,5), index='Land Seismic Geology Drilling Completions Production Facilities Midstream'.split(),\
    columns='Cycle_1 Cycle_2 Cycle_3 Cycle_4 Cycle_5'.split())
life_cycle

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5
Land        -1.749765  0.342680  1.153036 -0.252436  0.981321
Seismic      0.514219  0.221180 -1.070043 -0.189496  0.255001
Geology     -0.458027  0.435163 -0.583595  0.816847  0.672721
Drilling    -0.104411 -0.531280  1.029733 -0.438136 -1.118318
Completions  1.618982  1.541605 -0.251879 -0.842436  0.184519
Production   0.937082  0.731000  1.361556 -0.326238  0.055676
Facilities   0.222400 -1.443217 -0.756352  0.816454  0.750445
Midstream   -0.455947  1.189622 -1.690617 -1.356399 -1.232435

In [108]:
life_cycle.head(2)

Cycle_1  Cycle_2   Cycle_3   Cycle_4   Cycle_5
Land    -1.749765  0.34268  1.153036 -0.252436  0.981321
Seismic  0.514219  0.22118 -1.070043 -0.189496  0.255001

In [109]:
life_cycle.tail(2)

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5
Facilities  0.222400 -1.443217 -0.756352  0.816454  0.750445
Midstream  -0.455947  1.189622 -1.690617 -1.356399 -1.232435

In [110]:
life_cycle.describe()

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5
count  8.000000  8.000000  8.000000  8.000000  8.000000
mean   0.065566  0.310844 -0.101020 -0.221480  0.068616
std    1.019031  0.946721  1.142760  0.745362  0.829178
min   -1.749765 -1.443217 -1.690617 -1.356399 -1.232435
25%   -0.456467  0.033065 -0.834775 -0.539211 -0.237823
50%    0.058994  0.388922 -0.417737 -0.289337  0.219760
75%    0.619935  0.845656  1.060558  0.061992  0.692152
max    1.618982  1.541605  1.361556  0.816847  0.981321

In [111]:
life_cycle.cumsum()

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5
Land        -1.749765  0.342680  1.153036 -0.252436  0.981321
Seismic     -1.235547  0.563860  0.082992 -0.441932  1.236322
Geology     -1.693574  0.999024 -0.500603  0.374915  1.909043
Drilling    -1.797985  0.467743  0.529130 -0.063220  0.790725
Completions -0.179003  2.009348  0.277251 -0.905656  0.975243
Production   0.758079  2.740349  1.638807 -1.231894  1.030919
Facilities   0.980479  1.297132  0.882455 -0.415440  1.781364
Midstream    0.524532  2.486754 -0.808162 -1.771839  0.548930

In [112]:
life_cycle['Cycle_2']

Land           0.342680
Seismic        0.221180
Geology        0.435163
Drilling      -0.531280
Completions    1.541605
Production     0.731000
Facilities    -1.443217
Midstream      1.189622
Name: Cycle_2, dtype: float64

In [114]:
life_cycle['Cycle_2']

Land           0.342680
Seismic        0.221180
Geology        0.435163
Drilling      -0.531280
Completions    1.541605
Production     0.731000
Facilities    -1.443217
Midstream      1.189622
Name: Cycle_2, dtype: float64

In [115]:
life_cycle.Cycle_2

Land           0.342680
Seismic        0.221180
Geology        0.435163
Drilling      -0.531280
Completions    1.541605
Production     0.731000
Facilities    -1.443217
Midstream      1.189622
Name: Cycle_2, dtype: float64

In [116]:
life_cycle[['Cycle_2', 'Cycle_3']]

Cycle_2   Cycle_3
Land         0.342680  1.153036
Seismic      0.221180 -1.070043
Geology      0.435163 -0.583595
Drilling    -0.531280  1.029733
Completions  1.541605 -0.251879
Production   0.731000  1.361556
Facilities  -1.443217 -0.756352
Midstream    1.189622 -1.690617

In [117]:
life_cycle['Cycle_Total']=life_cycle['Cycle_1']+life_cycle\
    ['Cycle_2']+life_cycle['Cycle_3']+life_cycle['Cycle_4']+\
    life_cycle['Cycle_5']
life_cycle['Cycle_Total']

Land           0.474835
Seismic       -0.269139
Geology        0.883109
Drilling      -1.162413
Completions    2.250791
Production     2.759077
Facilities    -0.410271
Midstream     -3.545775
Name: Cycle_Total, dtype: float64

In [118]:
life_cycle['Cycle_1_2_Mult']=life_cycle['Cycle_1']*life_cycle['Cycle_2']
life_cycle['Cycle_1_2_Mult']

Land          -0.599610
Seismic        0.113735
Geology       -0.199317
Drilling       0.055472
Completions    2.495831
Production     0.685007
Facilities    -0.320971
Midstream     -0.542405
Name: Cycle_1_2_Mult, dtype: float64

In [119]:
life_cycle

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5  Cycle_Total  \
Land        -1.749765  0.342680  1.153036 -0.252436  0.981321     0.474835   
Seismic      0.514219  0.221180 -1.070043 -0.189496  0.255001    -0.269139   
Geology     -0.458027  0.435163 -0.583595  0.816847  0.672721     0.883109   
Drilling    -0.104411 -0.531280  1.029733 -0.438136 -1.118318    -1.162413   
Completions  1.618982  1.541605 -0.251879 -0.842436  0.184519     2.250791   
Production   0.937082  0.731000  1.361556 -0.326238  0.055676     2.759077   
Facilities   0.222400 -1.443217 -0.756352  0.816454  0.750445    -0.410271   
Midstream   -0.455947  1.189622 -1.690617 -1.356399 -1.232435    -3.545775   

             Cycle_1_2_Mult  
Land              -0.599610  
Seismic            0.113735  
Geology           -0.199317  
Drilling           0.055472  
Completions        2.495831  
Production         0.685007  
Facilities        -0.320971  
Midstream         -0.542405

In [120]:
life_cycle.drop(labels=['Cycle_Total', 'Cycle_1_2_Mult'], axis=1, inplace=True)
life_cycle

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5
Land        -1.749765  0.342680  1.153036 -0.252436  0.981321
Seismic      0.514219  0.221180 -1.070043 -0.189496  0.255001
Geology     -0.458027  0.435163 -0.583595  0.816847  0.672721
Drilling    -0.104411 -0.531280  1.029733 -0.438136 -1.118318
Completions  1.618982  1.541605 -0.251879 -0.842436  0.184519
Production   0.937082  0.731000  1.361556 -0.326238  0.055676
Facilities   0.222400 -1.443217 -0.756352  0.816454  0.750445
Midstream   -0.455947  1.189622 -1.690617 -1.356399 -1.232435

In [123]:
life_cycle.drop(labels=['Land', 'Seismic'], axis=0, inplace=True)
life_cycle

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5
Geology     -0.458027  0.435163 -0.583595  0.816847  0.672721
Drilling    -0.104411 -0.531280  1.029733 -0.438136 -1.118318
Completions  1.618982  1.541605 -0.251879 -0.842436  0.184519
Production   0.937082  0.731000  1.361556 -0.326238  0.055676
Facilities   0.222400 -1.443217 -0.756352  0.816454  0.750445
Midstream   -0.455947  1.189622 -1.690617 -1.356399 -1.232435

Loc and iloc

In [124]:
from numpy.random import randn
seed=200
np.random.seed(200)
matrix=pd.DataFrame(randn(5,5), columns='Cycle_1 Cycle_2 Cycle_3 Cycle_4 Cycle_5'.split())
matrix

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5
0 -1.450948  1.910953  0.711879 -0.247738  0.361466
1 -0.032950 -0.221347  0.477257 -0.691939  0.792006
2  0.073249  1.303286  0.213481  1.017349  1.911712
3 -0.529672  1.842135 -1.057235 -0.862916  0.237631
4 -1.154182  1.214984 -1.293759  0.822723 -0.332151

In [126]:
matrix.loc[0:2,:]

Cycle_1   Cycle_2   Cycle_3   Cycle_4   Cycle_5
0 -1.450948  1.910953  0.711879 -0.247738  0.361466
1 -0.032950 -0.221347  0.477257 -0.691939  0.792006
2  0.073249  1.303286  0.213481  1.017349  1.911712

In [127]:
matrix.loc[:,['Cycle_1', 'Cycle_2']]

Cycle_1   Cycle_2
0 -1.450948  1.910953
1 -0.032950 -0.221347
2  0.073249  1.303286
3 -0.529672  1.842135
4 -1.154182  1.214984

In [129]:
matrix.loc[0:3,['Cycle_3', 'Cycle_5']]

Cycle_3   Cycle_5
0  0.711879  0.361466
1  0.477257  0.792006
2  0.213481  1.911712
3 -1.057235  0.237631

In [130]:
matrix.iloc[:,0:2]

Cycle_1   Cycle_2
0 -1.450948  1.910953
1 -0.032950 -0.221347
2  0.073249  1.303286
3 -0.529672  1.842135
4 -1.154182  1.214984

In [132]:
matrix.iloc[2,4]

1.9117117810216346

In [133]:
matrix.iloc[[0,2,4],[0,2,4]]

Cycle_1   Cycle_3   Cycle_5
0 -1.450948  0.711879  0.361466
2  0.073249  0.213481  1.911712
4 -1.154182 -1.293759 -0.332151

Conditional selectin

In [134]:
from numpy.random import randn
seed=400
np.random.seed(seed)
Decision=pd.DataFrame(randn(8,4),columns='Drill No_Drill Frac No_Frac'.split())
Decision

Drill  No_Drill      Frac   No_Frac
0 -1.130571  0.696200 -0.432293  0.741020
1 -0.478137  1.386040  0.125180  1.148860
2 -2.350259  0.183293 -0.311386 -0.294066
3  0.400061  1.005500  0.501643 -0.000668
4  1.303972  1.073324 -0.515345  1.662900
5  0.551817 -0.579494 -0.848800 -0.410862
6  2.160625 -1.557699  0.134852  0.005454
7  0.646549 -0.592073  0.551924  1.378349

In [135]:
Decision>0

Drill  No_Drill   Frac  No_Frac
0  False      True  False     True
1  False      True   True     True
2  False      True  False    False
3   True      True   True    False
4   True      True  False     True
5   True     False  False    False
6   True     False   True     True
7   True     False   True     True

In [136]:
Decision['Drill']>0

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7     True
Name: Drill, dtype: bool

In [137]:
Decision[Decision['Drill']>0]

Drill  No_Drill      Frac   No_Frac
3  0.400061  1.005500  0.501643 -0.000668
4  1.303972  1.073324 -0.515345  1.662900
5  0.551817 -0.579494 -0.848800 -0.410862
6  2.160625 -1.557699  0.134852  0.005454
7  0.646549 -0.592073  0.551924  1.378349

In [141]:
Decision[(Decision['Drill']>0)&(Decision['No_Drill']>0)&(Decision['Frac']>0)&(Decision['No_Frac']<0)]

Drill  No_Drill      Frac   No_Frac
3  0.400061    1.0055  0.501643 -0.000668

Pandas Groupby

In [148]:
df=pd.DataFrame({'Corporation_Name':['CVX','EXXON','CVX','EXXON','GE','GE'], 'Sales_Person':['Adam','Alex','Bruce',\
                 'Jessica', 'Natalie','Rachel'],'Sales_Amount':[2000,5000,10000,45000,60000,20000]})
df

Corporation_Name Sales_Person  Sales_Amount
0              CVX         Adam          2000
1            EXXON         Alex          5000
2              CVX        Bruce         10000
3            EXXON      Jessica         45000
4               GE      Natalie         60000
5               GE       Rachel         20000

In [149]:
df_group_by=df.groupby('Corporation_Name')
df_group_by.mean(numeric_only=True)

Sales_Amount
Corporation_Name              
CVX                     6000.0
EXXON                  25000.0
GE                     40000.0

In [150]:
df.groupby('Corporation_Name').mean(numeric_only=True)

Sales_Amount
Corporation_Name              
CVX                     6000.0
EXXON                  25000.0
GE                     40000.0

In [152]:
df_group_by.std(numeric_only=True)

Sales_Amount
Corporation_Name              
CVX                5656.854249
EXXON             28284.271247
GE                28284.271247

In [153]:
df.groupby('Corporation_Name').describe().transpose()

Corporation_Name             CVX         EXXON            GE
Sales_Amount count      2.000000      2.000000      2.000000
             mean    6000.000000  25000.000000  40000.000000
             std     5656.854249  28284.271247  28284.271247
             min     2000.000000   5000.000000  20000.000000
             25%     4000.000000  15000.000000  30000.000000
             50%     6000.000000  25000.000000  40000.000000
             75%     8000.000000  35000.000000  50000.000000
             max    10000.000000  45000.000000  60000.000000

Pandas data frame concatenation

In [155]:
df1=pd.DataFrame({'A':['H1','H2','H3','H4'],
'B':['I1','I2','I3','I4'],'C':['J1','J2','J3','J4'],
'D':['K1','K2','K3','K4']}, index=[0,1,2,3])

In [156]:
df1

A   B   C   D
0  H1  I1  J1  K1
1  H2  I2  J2  K2
2  H3  I3  J3  K3
3  H4  I4  J4  K4

In [157]:
df2=pd.DataFrame({'A':['H5','H6','H7','H8'],
'B':['I5','I6','I7','I8'], 'C':['J5','J6','J7','J8'],
'D':['K5','K6','K7','K8']}, index=[4,5,6,7])

In [158]:
df2

A   B   C   D
4  H5  I5  J5  K5
5  H6  I6  J6  K6
6  H7  I7  J7  K7
7  H8  I8  J8  K8

In [159]:
df3=pd.DataFrame({'A':['H9','H10','H11','H12'],
'B':['I9','I10','I11','I12'],'C':['J9','J10','J11','J12'],
'D':['K9','K10','K11','K12'],'E':['L1','L2','L3','L4']},
index=[8,9,10,11])

In [160]:
df3


A    B    C    D   E
8    H9   I9   J9   K9  L1
9   H10  I10  J10  K10  L2
10  H11  I11  J11  K11  L3
11  H12  I12  J12  K12  L4

In [162]:
pd.concat([df1,df2,df3])

A    B    C    D    E
0    H1   I1   J1   K1  NaN
1    H2   I2   J2   K2  NaN
2    H3   I3   J3   K3  NaN
3    H4   I4   J4   K4  NaN
4    H5   I5   J5   K5  NaN
5    H6   I6   J6   K6  NaN
6    H7   I7   J7   K7  NaN
7    H8   I8   J8   K8  NaN
8    H9   I9   J9   K9   L1
9   H10  I10  J10  K10   L2
10  H11  I11  J11  K11   L3
11  H12  I12  J12  K12   L4

In [163]:
pd.concat([df1,df2,df3], axis=1)

A    B    C    D    A    B    C    D    A    B    C    D    E
0    H1   I1   J1   K1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    H2   I2   J2   K2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    H3   I3   J3   K3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    H4   I4   J4   K4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   H5   I5   J5   K5  NaN  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   H6   I6   J6   K6  NaN  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   H7   I7   J7   K7  NaN  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   H8   I8   J8   K8  NaN  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   H9   I9   J9   K9   L1
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  H10  I10  J10  K10   L2
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  H11  I11  J11  K11   L3
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  H12  I12  J12  K12   L4

In [164]:
test1=pd.DataFrame({'A':['X1','X2','X3','X4'],
'B':['Y1','Y2','Y3','Y4'], 'unique_ID':['Z1','Z2','Z3',
'Z5'],})
test2=pd.DataFrame({'C':['L1','L2','L3','L4'],
'D':['M1','M2','M3','M4'], 'unique_ID':['Z1','Z2','Z3','Z6']})


In [165]:
test1

A   B unique_ID
0  X1  Y1        Z1
1  X2  Y2        Z2
2  X3  Y3        Z3
3  X4  Y4        Z5

In [166]:
test2

C   D unique_ID
0  L1  M1        Z1
1  L2  M2        Z2
2  L3  M3        Z3
3  L4  M4        Z6

In [167]:
pd.merge(test1,test2, on='unique_ID', how='inner')

A   B unique_ID   C   D
0  X1  Y1        Z1  L1  M1
1  X2  Y2        Z2  L2  M2
2  X3  Y3        Z3  L3  M3

In [168]:
pd.merge(test1,test2, on='unique_ID', how='outer')

A    B unique_ID    C    D
0   X1   Y1        Z1   L1   M1
1   X2   Y2        Z2   L2   M2
2   X3   Y3        Z3   L3   M3
3   X4   Y4        Z5  NaN  NaN
4  NaN  NaN        Z6   L4   M4

In [169]:
test3=pd.DataFrame({'A':['X1','X2','X3','X4'],'B':['Y1','Y2','Y3','Y4'],
'unique_ID_1':['Z1','Z2','Z5','Z6'],
'unique_ID_2':['N1','N2','N6','N7']})

In [170]:
test4=pd.DataFrame({'C':['L1','L2','L3','L4'],'D':['M1','M2',
'M3','M4'],'unique_ID_1':['Z1','Z2','Z9','Z10'],
'unique_ID_2':['N1','N2','N11','N12']})

In [171]:
test3

A   B unique_ID_1 unique_ID_2
0  X1  Y1          Z1          N1
1  X2  Y2          Z2          N2
2  X3  Y3          Z5          N6
3  X4  Y4          Z6          N7

In [172]:
test4

C   D unique_ID_1 unique_ID_2
0  L1  M1          Z1          N1
1  L2  M2          Z2          N2
2  L3  M3          Z9         N11
3  L4  M4         Z10         N12

In [173]:
pd.merge(test3, test4, on=['unique_ID_1','unique_ID_2'], how='inner')

A   B unique_ID_1 unique_ID_2   C   D
0  X1  Y1          Z1          N1  L1  M1
1  X2  Y2          Z2          N2  L2  M2

Pandas Joining

In [176]:
test5=pd.DataFrame({'A':['X1','X2','X3','X4'],
'B':['Y1','Y2','Y3','Y4']}, index=['H1','H2','H3','H4'])
test6=pd.DataFrame({'C':['X1','X2','X3','X4'],
'D':['Y1','Y2','Y3','Y4']}, index=['H2','H3','H1','H0'])


In [177]:
test5


A   B
H1  X1  Y1
H2  X2  Y2
H3  X3  Y3
H4  X4  Y4

In [178]:
test6

C   D
H2  X1  Y1
H3  X2  Y2
H1  X3  Y3
H0  X4  Y4

In [179]:
test5.join(test6, how='inner')

A   B   C   D
H1  X1  Y1  X3  Y3
H2  X2  Y2  X1  Y1
H3  X3  Y3  X2  Y2

In [180]:
test5.join(test6, how='outer')

A    B    C    D
H0  NaN  NaN   X4   Y4
H1   X1   Y1   X3   Y3
H2   X2   Y2   X1   Y1
H3   X3   Y3   X2   Y2
H4   X4   Y4  NaN  NaN

Pandas operations

In [181]:
df_ops=pd.DataFrame({'A':[24,21,74,21],
'B':[32,31,65,54],'C':['a','b','c','d']})

In [182]:
df_ops

A   B  C
0  24  32  a
1  21  31  b
2  74  65  c
3  21  54  d

In [183]:
df_ops['A'].unique()

array([24, 21, 74])

In [184]:
df_ops['A'].nunique()

3

In [185]:
df_ops.nunique()

A    3
B    4
C    4
dtype: int64

In [186]:
df_ops['B'].value_counts()

B
32    1
31    1
65    1
54    1
Name: count, dtype: int64

In [187]:
df_ops['A'].value_counts()

A
21    2
24    1
74    1
Name: count, dtype: int64

In [189]:
df_ops[(df_ops['A']>=20)&(df_ops['B']>=35)&(df_ops['C']=='c')]

A   B  C
2  74  65  c

In [190]:
def economics(x):
    return x**2
df_ops['A'].apply(economics)

0     576
1     441
2    5476
3     441
Name: A, dtype: int64

Pandas lambda expression

In [191]:
df_ops['B'].apply(lambda x:x*4)

0    128
1    124
2    260
3    216
Name: B, dtype: int64

In [192]:
df_ops['D']=df_ops['A'].apply(lambda x:x**2+1)

In [193]:
df_ops

A   B  C     D
0  24  32  a   577
1  21  31  b   442
2  74  65  c  5477
3  21  54  d   442

In [194]:
df_ops['E']=df_ops['B'].apply(lambda x: x**3+x**2+1)

In [196]:
df_ops['F']=df_ops['A'].apply(lambda x: x**4+x**2+5)

In [197]:
df_ops['G']=df_ops['B'].apply(lambda x: x**2+10)

In [198]:
df_ops['ALL']=df_ops['A'].apply(lambda x:x**2+10)+df_ops['A'].apply(lambda x:x**2+10)

In [199]:
df_ops

A   B  C     D       E         F     G    ALL
0  24  32  a   577   33793    332357  1034   1172
1  21  31  b   442   30753    194927   971    902
2  74  65  c  5477  278851  29992057  4235  10972
3  21  54  d   442  160381    194927  2926    902

In [200]:
df_ops.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'ALL'], dtype='object')

In [204]:
df_ops.sort_values('ALL', ascending=True)

A   B  C     D       E         F     G    ALL
1  21  31  b   442   30753    194927   971    902
3  21  54  d   442  160381    194927  2926    902
0  24  32  a   577   33793    332357  1034   1172
2  74  65  c  5477  278851  29992057  4235  10972

Dealing with missing values in Pandas

In [205]:
import pandas as pd
import numpy as np
df_missing=pd.DataFrame({'A':[1,20,31,43,59,np.nan,6,4,5,2,5,6,7,3,np.nan],\
    'B':[1,20,np.nan,43,52,32,6,9,5,2,90,6,np.nan,3,100],\
    'C':[1,30,68,43,np.nan,32,6,4,np.nan,2,5,6,888,3,100]})

In [206]:
df_missing

A      B      C
0    1.0    1.0    1.0
1   20.0   20.0   30.0
2   31.0    NaN   68.0
3   43.0   43.0   43.0
4   59.0   52.0    NaN
5    NaN   32.0   32.0
6    6.0    6.0    6.0
7    4.0    9.0    4.0
8    5.0    5.0    NaN
9    2.0    2.0    2.0
10   5.0   90.0    5.0
11   6.0    6.0    6.0
12   7.0    NaN  888.0
13   3.0    3.0    3.0
14   NaN  100.0  100.0

In [207]:
df_missing.head(5)

A     B     C
0   1.0   1.0   1.0
1  20.0  20.0  30.0
2  31.0   NaN  68.0
3  43.0  43.0  43.0
4  59.0  52.0   NaN

In [208]:
df_missing.dropna(how='any')

A     B     C
0    1.0   1.0   1.0
1   20.0  20.0  30.0
3   43.0  43.0  43.0
6    6.0   6.0   6.0
7    4.0   9.0   4.0
9    2.0   2.0   2.0
10   5.0  90.0   5.0
11   6.0   6.0   6.0
13   3.0   3.0   3.0

In [211]:
df_missing.dropna(how='any', axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [212]:
df_filling=pd.DataFrame({'A':[43,59,np.nan,6,3,np.nan],'B':[1,20,np.nan,43,np.nan,32],'C':[np.nan,32,6,4,np.nan,2]})

In [213]:
df_filling

A     B     C
0  43.0   1.0   NaN
1  59.0  20.0  32.0
2   NaN   NaN   6.0
3   6.0  43.0   4.0
4   3.0   NaN   NaN
5   NaN  32.0   2.0

In [214]:
df_filling.fillna(value='Hydraulic Fracturing', inplace=True)

/var/folders/y6/fxl5q2qn5kg2cd_4j_k391qm0000gn/T/ipykernel_49122/922927716.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Hydraulic Fracturing' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_filling.fillna(value='Hydraulic Fracturing', inplace=True)


In [215]:
df_filling

A                     B                     C
0                  43.0                   1.0  Hydraulic Fracturing
1                  59.0                  20.0                  32.0
2  Hydraulic Fracturing  Hydraulic Fracturing                   6.0
3                   6.0                  43.0                   4.0
4                   3.0  Hydraulic Fracturing  Hydraulic Fracturing
5  Hydraulic Fracturing                  32.0                   2.0

In [216]:
df_filling_mean=pd.DataFrame({'A':[43,59,np.nan,6,3,np.nan],
'B':[1,20,np.nan,43,np.nan,32],'C':[np.nan,32,6,4,np.nan,2]})

In [217]:
df_filling_mean

A     B     C
0  43.0   1.0   NaN
1  59.0  20.0  32.0
2   NaN   NaN   6.0
3   6.0  43.0   4.0
4   3.0   NaN   NaN
5   NaN  32.0   2.0

In [220]:
df_filling_mean.fillna(value=df_filling_mean.mean(), inplace=True)

In [221]:
df_filling_mean

A     B     C
0  43.00   1.0  11.0
1  59.00  20.0  32.0
2  27.75  24.0   6.0
3   6.00  43.0   4.0
4   3.00  24.0  11.0
5  27.75  32.0   2.0

In [226]:
df_filling_backfill=pd.DataFrame({'A':[43,59,np.nan,6,3,np.nan],\
    'B':[1,20,np.nan,43,np.nan,32],'C':[np.nan,32,6,4,np.nan,2]})
df_filling_backfill


A     B     C
0  43.0   1.0   NaN
1  59.0  20.0  32.0
2   NaN   NaN   6.0
3   6.0  43.0   4.0
4   3.0   NaN   NaN
5   NaN  32.0   2.0

In [227]:
df_filling_backfill.fillna(method='bfill')

/var/folders/y6/fxl5q2qn5kg2cd_4j_k391qm0000gn/T/ipykernel_49122/4061973333.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filling_backfill.fillna(method='bfill')


A     B     C
0  43.0   1.0  32.0
1  59.0  20.0  32.0
2   6.0  43.0   6.0
3   6.0  43.0   4.0
4   3.0  32.0   2.0
5   NaN  32.0   2.0

In [228]:
import numpy as np
A=[1,2,3,4,5,6,7,8,9,10]
np.array(A)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [229]:
B=[[4,5,6],[7,8,9],[10,11,12]]

In [230]:
np.array(B)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [234]:
np.arange(0,40,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [235]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [236]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [237]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [238]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [239]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [240]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [241]:
seed=100
np.random.seed(seed)
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [242]:
seed=100
np.random.seed(seed)
np.random.rand(5,5)

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
       [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
       [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
       [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375],
       [0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045]])

In [243]:
seed=100
np.random.seed(seed)
np.random.randn(5)

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [244]:
seed=100
np.random.seed(seed)
np.random.randn(5,5)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079],
       [ 0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081],
       [-0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869]])

In [245]:
np.random.randint(1,500,10)

array([ 14, 107,  31,  18,  54,  69, 435, 489, 348, 476])

In [247]:
A=np.arange(20,30)

In [248]:
A

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [249]:
A.reshape(5,2)

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [250]:
X=np.arange(30,41)

In [251]:
X

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [252]:
X[:7]

array([30, 31, 32, 33, 34, 35, 36])

In [253]:
X[2:]

array([32, 33, 34, 35, 36, 37, 38, 39, 40])

In [255]:
Y=X.copy()*2

In [256]:
Y

array([60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80])

In [257]:
Y[:5]=1000
Y

array([1000, 1000, 1000, 1000, 1000,   70,   72,   74,   76,   78,   80])

In [259]:
array_2d=np.array([[50,52,54],[56,58,60],[62,64,66],[68,70,72]])
array_2d

array([[50, 52, 54],
       [56, 58, 60],
       [62, 64, 66],
       [68, 70, 72]])

In [260]:
array_2d[2][1]

64

In [261]:
array_2d[2:][1:]

array([[68, 70, 72]])

In [262]:
array_2d[2:,1:]

array([[64, 66],
       [70, 72]])

In [264]:
array_2d[3,:2]

array([68, 70])